-- migration: add timezone column to households and auto_generated flag to reports
-- purpose: align database schema with api requirements for household timezone and report provenance tracking
-- affects: public.households (timezone column), public.reports (auto_generated column)
-- notes: timezone remains optional to mirror api contract; auto_generated defaults to false for existing manual reports

alter table public.households
  add column if not exists timezone text;

comment on column public.households.timezone is
  'optional iana timezone identifier for the household (e.g., Europe/Warsaw)';

alter table public.reports
  add column if not exists auto_generated boolean not null default false;

comment on column public.reports.auto_generated is
  'indicates whether the report was auto-generated by system processes';
